### ISSUE TITLE
Missing images etc.

### ISSUE THREAD

**Issue by bep** [coryshaw/hugo-aurora-theme#1]
Some issues with your layout that prevent us from include it on themes.gohugo.io:

```
cp: exampleSite/themes/aurora/images/screenshot.png: No such file or directory
cp: exampleSite/themes/aurora/images/tn.png: No such file or directory
Building site for theme aurora using its own exampleSite
Example site for theme aurora missing /static folder
```

**Comment by coryshaw** [comment]
Thanks for the feedback. By the looks of it I need to include a screenshot and thumbnail. Will do that shortly and follow up with you when ready.

**Comment by coryshaw** [comment]
Fixed in the latest version.
