### ISSUE TITLE
Italic Text indented to the end of the line?

### ISSUE THREAD

**Issue by jjhartman** [coryshaw/hugo-aurora-theme#3]
For some reason whenever text is marked as italics (markup) using either _text_ or *text*, the entire word is moved to the end of the line, generating a large gap.  This is not the case for other styles, such as bold or strikethrough, but I can't figure out why italics are rendering this way.  
![screenshot 29](https://cloud.githubusercontent.com/assets/25942525/23242397/8656dbe2-f946-11e6-9b2d-e532368eb131.png)
![screenshot 30](https://cloud.githubusercontent.com/assets/25942525/23242396/86559944-f946-11e6-973a-0fc5a8e15ec6.png)
![screenshot 32](https://cloud.githubusercontent.com/assets/25942525/23242398/86655f78-f946-11e6-86fd-55c2b6055141.png)

 Examples attached.

**Comment by coryshaw** [comment]
Resolved in v1.3.4
